Использовать препроцессор для создания страниц приложения "блог"
vasiliev-alexey/otus_js_blog pull request #1
Opened 2021-03-13 12:49 UTC by vasiliev-alexey

### Использовать препроцессор для создания страниц приложения "блог" - сверстанные страницы должны быть доступны на githubpages

#### Цель: В результате выполнения ДЗ вы создадите верстку для вашего личного блога с использование препроцессора SASS(/LESS)

##### В данном задании тренируются навыки:

- верстки страниц
- использование принципов DRY при верстке
- использование препроцессоров
- деплой страниц на сервис github pages

##### Необходимо:

- создать новый репозиторий
- настроить в нем линтеры, github actions
- включить проверку линтером при PR
- включить деплой приложения при PR
- создать сайт-блог с минимум 4мя страницами (главная, обратная связь, список записей, страница записи)
- создать PR с изменениями
- сбросить ссылку на PR и ссылку на задеплоенные страницы в част с преподавателем

2021-03-15 17:27 UTC, AntiHero requested changes

2021-03-15 17:27 UTC, AntiHero commented on pages/login.html
> +      <table class="login__form__table">
пройтись по всем .html исправить ошибки по БЭМ

2021-03-15 17:27 UTC, AntiHero commented on pages/parts/footer.html
> +  <picture class="facebook"></picture>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

2021-03-15 17:29 UTC, AntiHero commented
- поправить скролл
- добавить паддинги

2021-03-16 18:51 UTC, vasiliev-alexey commented
Правим:

- [x] Сменить язык для страниц
- [x] пройтись по всем html исправить ошибки по БЭМ
- [x] исправить picture
- [x] поправить скролл страницы
- [x] добавить паддинги
- [x] На странице с постами - опустить панель пейджинга вниз
- [x] Переверстать страницу авторизации
- [x] Размер картинки подобрать подходящий
- [x] В панели навигации по базовой линии выстроить элементы

2021-03-16 19:36 UTC, AntiHero requested changes

2021-03-16 19:36 UTC, AntiHero commented on pages/login.html
> +        <input type="password" name="pass" class="loginForm__username" />
обычно дают разные классы (например loginForm__username, loginFrom__password) т.к. это разные по назначению элементы, но присваивают одинаковые стили

2021-03-16 19:36 UTC, AntiHero commented on pages/parts/feedback_form.html
> +      id="postForm--title"
так id писать не надо (как модификатор по БЭМ), чтобы не путаться, можешь написать postForm-title, например

2021-03-16 19:36 UTC, AntiHero commented on pages/parts/post.html
> +      id="post_title"
тут тоже

2021-03-16 19:36 UTC, AntiHero commented on pages/parts/posts.html
> +<main class="main__posts">
опять же, начинаешь с элемента, а должен начать с блока, т.е `main-posts` в твоём случае или просто `main`

2021-03-16 19:36 UTC, AntiHero commented on pages/parts/posts.html
> +<footer class="main__footer">
тут тоже, и при чём тут main? почему не просто footer?

2021-03-16 19:36 UTC, AntiHero commented on pages/parts/sidebar.html
> +  <footer class="aside__main">
а это что? что за footer в aside? и main в aside? main - это основной контент, aside - косвенный, как получилось что у тебя основной контент в косвенном и ещё и footer, который является "подвалом" html cтраницы

2021-03-17 10:00 UTC, AntiHero approved these changes

2021-03-17 10:05 UTC, merged